apiVersion: v1
kind: Secret
metadata:
  name: trojan-tls-cert
  namespace: trojan
  labels:
    environment: production
    app: trojan
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    YOUR+CERTIFICATE+HERE
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    YOUR+PRIVATE+KEY+HERE
    -----END PRIVATE KEY-----
