apiVersion: v1
kind: Service
metadata:
  name: trojan-service
  namespace: trojan
  labels:
    environment: production
    app: trojan
spec:
  type: LoadBalancer
  selector:
    app: trojan
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
