apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: trojan
  labels:
    environment: production
    app: phpmyadmin
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
