apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: trojan
  labels:
    environment: production
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env:
        - name: PMA_HOST
          value: mariadb-service
        ports:
        - containerPort: 80
