apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: trojan
  labels:
    environment: production
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: site-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: site-config
        configMap:
          name: nginx-site-config
          items:
          - key: site-config
            path: default.conf
