apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: trojan
  labels:
    environment: production
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
