apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: trojan
  labels:
    environment: production
    app: mariadb
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
